# Generated by Django 4.2 on 2023-05-16 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_donor_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodrequest',
            name='approving_doctor',
        ),
    ]
