# Generated by Django 4.2 on 2023-05-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_invitation_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='donation_count',
            field=models.IntegerField(default=0),
        ),
    ]
