# Generated by Django 4.2 on 2023-05-23 12:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_donor_donation_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_active_donors', models.IntegerField(default=0)),
                ('total_donations_active_donors', models.IntegerField(default=0)),
                ('total_reserve_donors', models.IntegerField(default=0)),
                ('total_donations_reserve_donors', models.IntegerField(default=0)),
                ('total_donors', models.IntegerField(default=0)),
                ('total_primary_donors', models.IntegerField(default=0)),
                ('total_plasma_donors', models.IntegerField(default=0)),
                ('total_immune_donors', models.IntegerField(default=0)),
                ('total_isoimmune_donors', models.IntegerField(default=0)),
                ('total_blood_cell_donors', models.IntegerField(default=0)),
                ('total_donations', models.IntegerField(default=0)),
                ('total_plasma_donations', models.IntegerField(default=0)),
                ('total_reserve_donations', models.IntegerField(default=0)),
                ('total_plasma_units', models.IntegerField(default=0)),
                ('total_reserve_plasma_units', models.IntegerField(default=0)),
                ('total_single_plasma_units', models.IntegerField(default=0)),
                ('total_double_plasma_units', models.IntegerField(default=0)),
                ('total_machine_plasma_units', models.IntegerField(default=0)),
                ('total_blood_units', models.IntegerField(default=0)),
                ('total_reserve_blood_units', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_date', models.DateField(default=django.utils.timezone.now)),
                ('donation_type', models.CharField(max_length=50)),
                ('plasma_units', models.IntegerField(default=0)),
                ('blood_units', models.IntegerField(default=0)),
                ('blood_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='donation', to='main_app.bloodrequest')),
            ],
        ),
    ]
