# Generated by Django 4.2 on 2023-05-23 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_alter_donation_blood_request'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Statistics',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='is_permanent_donor',
        ),
    ]
