# Generated by Django 4.2 on 2023-05-23 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_delete_statistics_remove_donor_is_permanent_donor'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='is_permanent_donor',
            field=models.BooleanField(default=False),
        ),
    ]
