# Generated by Django 4.2 on 2023-05-23 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_donor_is_permanent_donor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='is_permanent_donor',
        ),
    ]
