# Generated by Django 4.2 on 2023-05-23 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_remove_donor_is_permanent_donor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='blood_units',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='donation',
            name='plasma_units',
            field=models.FloatField(default=0),
        ),
    ]
